# path_classifiers:
#   foo:
#     - "*.cpp"
#     - "OpenMEEG/*/*.cpp"
#     - "OpenMEEGMaths/*/*.cpp"
#   exclude:
#     - "wrapping/"
#     - "build_tools/"
#   test:
#     - "tests/*.cpp"

extraction:
  cpp:
    prepare:
      packages:
        - libopenblas-dev
        - liblapacke-dev # XXX: If lapacke is missing, cmake does not break at generation but at compilation.
      command:
        - mkdir -p _lgtm_build_dir

    configure:
      command:
        - cd _lgtm_build_dir
        - cmake -DBLA_VENDOR=OpenBLAS ..

    index:
      build_command:
        - cd _lgtm_build_dir
        - make
