language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang
      env: USE_SYSTEM=0
    - os: linux
      compiler: gcc
      env: USE_SYSTEM=0
    - os: linux
      compiler: gcc
      env: USE_SYSTEM=1

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script:
  - $CXX --version
  - make test-OpenMEEG
  - cpack -G TGZ .
