language: cpp

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

compiler:
  - clang
  - gcc

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script:
  - $CXX --version
  - ctest -V
