language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script:
  - $CXX --version
  - ctest -V
